# -*- coding: utf-8 -*-
"""KlasteringAHCExcel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v6Z5RKKCK8eP8W4R5oH2tvLLME7VrOHT
"""

# import library
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import numpy as np
import pandas as pd

data = pd.read_excel("Data AHC.xlsx")
print(data)

x = np.asarray(data)
print(x)

# lakukan hierarchical klastering
Z = linkage(x)

# plot dendrogram
plt.figure(figsize=(25, 10))
plt.title('Dendogram Hierarchical Klastering')
plt.xlabel('data')
plt.ylabel('jarak')
dendrogram(Z)
plt.show()