# -*- coding: utf-8 -*-
"""KlasteringAHC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JSETFKkz2chhv2dcBbCNWuRZDPdX1vqE
"""

# import library
from matplotlib import pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
import numpy as np

# buat array 2D ke dalam variabel x. Data ini yang akan kita klaster
x = np.array([[1,2],[2.5,4.5],[2,2],[4,1.5],[4,2.5]])

print(x)

# lakukan hierarchical klastering
Z = linkage(x)

print(Z)

# plot dendrogram
plt.figure(figsize=(25, 10))
plt.title('Dendogram Hierarchical Klastering')
plt.xlabel('data')
plt.ylabel('jarak')
dendrogram(Z)
plt.show()